import 'package:dony/features/payments/money/data/models/money_overview_model.dart';

/// Réponse type de `GET /payments/me/overview` (yadony-back #481).
Map<String, dynamic> overviewJson() => {
  'generatedAt': '2026-10-10T12:00:00Z',
  'recentWindowDays': 30,
  'wallet': [
    {'currency': 'EUR', 'balance': 96.1},
    {'currency': 'XOF', 'balance': 2000},
  ],
  'traveler': {
    'totals': [
      {'currency': 'EUR', 'upcoming': 0, 'releasedRecently': 26.4},
      {'currency': 'XOF', 'upcoming': 17400, 'releasedRecently': 0},
    ],
    'items': [
      {
        'bidId': 'bid-held',
        'trackingNumber': 'DON-5DD4K2QP',
        'announcementId': 'ann-1',
        'role': 'TRAVELER',
        'departureCity': 'Paris',
        'arrivalCity': 'Abidjan',
        'departureDate': '2026-10-14',
        'amount': 7950,
        'currency': 'XOF',
        'channel': 'MOBILE_MONEY',
        'state': 'RELEASE_SCHEDULED',
        'releaseCondition': 'AUTO_RELEASE_AFTER_HOLD_IF_NO_DISPUTE',
        'releaseAt': '2026-10-11T08:00:00Z',
        'counterpartyName': 'Awa K.',
        'bidStatus': 'ARRIVED',
        'weightKg': 10,
      },
      {
        'bidId': 'bid-escrow',
        'trackingNumber': 'DON-2A00XYZW',
        'role': 'TRAVELER',
        'departureCity': 'Paris',
        'arrivalCity': 'Abidjan',
        'departureDate': '2026-10-18',
        'amount': 9450,
        'currency': 'XOF',
        'channel': 'MOBILE_MONEY',
        'state': 'ESCROWED',
        'releaseCondition': 'ON_DELIVERY_CONFIRMATION',
        'counterpartyName': 'Fatou S.',
        'bidStatus': 'ACCEPTED',
      },
      {
        'bidId': 'bid-cash',
        'trackingNumber': 'DON-66VYH3MA',
        'role': 'TRAVELER',
        'departureCity': 'Abidjan',
        'arrivalCity': 'Ouagadougou',
        'currency': 'XOF',
        'channel': 'CASH',
        'state': 'CASH',
        'releaseCondition': 'CASH_IN_PERSON',
        'bidStatus': 'ACCEPTED',
        'cashCommissionStatus': 'CHARGED',
      },
      {
        'bidId': 'bid-released',
        'trackingNumber': 'DON-RLSD0001',
        'role': 'TRAVELER',
        'departureCity': 'Lyon',
        'arrivalCity': 'Dakar',
        'amount': 26.4,
        'currency': 'EUR',
        'channel': 'CARD',
        'state': 'RELEASED_RECENTLY',
        'releaseCondition': 'RELEASED',
        'settledAt': '2026-10-05T14:00:00Z',
        'bidStatus': 'COMPLETED',
      },
    ],
  },
  'sender': {
    'totals': [
      {
        'currency': 'EUR',
        'blocked': 150,
        'refundPending': 0,
        'refundedRecently': 40,
      },
    ],
    'items': [
      {
        'bidId': 'bid-sent',
        'trackingNumber': 'DON-SENT0001',
        'role': 'SENDER',
        'departureCity': 'Marseille',
        'arrivalCity': 'Douala',
        'amount': 150,
        'currency': 'EUR',
        'channel': 'CARD',
        'state': 'IN_DISPUTE',
        'releaseCondition': 'ADMIN_DECISION',
        'counterpartyName': 'Moussa K.',
        'bidStatus': 'IN_TRANSIT',
        'weightKg': 4.5,
      },
    ],
  },
};

MoneyOverviewModel overviewModel() =>
    MoneyOverviewModel.fromJson(overviewJson());

/// Montant minimal d'un colis pour les tests unitaires de présentation.
MoneyItemModel item({
  MoneyState state = MoneyState.escrowed,
  MoneyRole role = MoneyRole.traveler,
  String? bidStatus,
  DateTime? releaseAt,
  DateTime? settledAt,
  String? cashCommissionStatus,
  double? amount = 100,
  double? weightKg,
  DateTime? departureDate,
  String? counterpartyName,
}) => MoneyItemModel(
  bidId: 'bid-1',
  role: role,
  state: state,
  releaseCondition: ReleaseCondition.unknown,
  channel: MoneyChannel.card,
  trackingNumber: 'DON-TEST0001',
  departureCity: 'Paris',
  arrivalCity: 'Dakar',
  amount: amount,
  currency: 'EUR',
  bidStatus: bidStatus,
  releaseAt: releaseAt,
  settledAt: settledAt,
  cashCommissionStatus: cashCommissionStatus,
  weightKg: weightKg,
  departureDate: departureDate,
  counterpartyName: counterpartyName,
);
